---
- name: kubernetes
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Disabling Swap on all nodes
      shell: swapoff -a

    - name: Commenting Swap entries in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '(.*swap*)'
        replace: '#\1'

    - name: install pip
      apt:
        name: python-pip
        state: present

- name: kube-init
  hosts: all
  become: true
  roles:
    - kube-init

- name: master-cfg
  hosts: k8s-master
  become: true
  roles:
    - master-cfg
