---
- name: Initializate cluster
  command: kubeadm init --apiserver-advertise-address="192.168.33.101" --apiserver-cert-extra-sans="192.168.33.101"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
  args:
    chdir: $HOME
    creates: cluster_init.txt

- name: create .kube directory
  become_user: vagrant
  file:
    remote_src: yes
    path: /home/vagrant/.kube
    state: directory
    mode: 0755

- name: Copy admin conf to user's kube conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant

- name: install Pod network
  shell: "kubectl -n kube-system apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt"
  args:
    creates: pod_network_setup.txt
  environment:
    KUBECONFIG: "/home/vagrant/.kube/config"

- name: install Dashboard
  shell: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml"
  environment:
    KUBECONFIG: "/home/vagrant/.kube/config"

- name: curl helm
  shell: "curl https://baltocdn.com/helm/signing.asc | sudo apt-key add - "
  args:
    warn: no

- name: install apt-transport-https
  apt:
    force: yes
    name: apt-transport-https
    state: present

- name: baltocdn all main
  shell: "echo \"deb https://baltocdn.com/helm/stable/debian/ all main\" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list"

- name: Update Cache
  apt: update_cache=yes

- name: install helm
  apt:
    force: yes
    name: helm
    state: present

- name: Install calico pod network
  become: false
  shell: "kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml"
  environment:
    KUBECONFIG: "/home/vagrant/.kube/config"

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
