---
- name: Install NFS client
  apt:
    name: nfs-common
    state: present

- name: join cluster
  shell: "{{ hostvars['k8sMaster1'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt