---
- name: include_vars
  include_vars:
    file: vars.yml

#- name: Pick IP from the same network as master
#  set_fact: hostip="{{ ansible_all_ipv4_addresses|ipaddr(master_ip) }}"

- name: Ensure Kube APT KEY is present
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Ensure Kube APT Repo is present
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Ensure Docker APT KEY is present
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Update Cache
  apt: update_cache=yes

- name: Install container runtime
  apt:
    force: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

- name: Install kubelet kubeadm kubectl
  apt:
    force: yes
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Send bridge packets to iptables for processing
  block:
    - lineinfile:
        path: /etc/sysctl.conf
        line: net.bridge.bridge-nf-call-iptables=1
        create: yes
    - lineinfile:
        path: /etc/sysctl.conf
        line: net.bridge.bridge-nf-call-ip6tables=1
        create: yes
    - command: sysctl net.bridge.bridge-nf-call-iptables=1
    - command: sysctl net.bridge.bridge-nf-call-ip6tables=1

- name: Create /etc/default/kubelet with extra args
  template:
    src: kubelet.j2
    dest: /etc/default/kubelet