---
- name: Add incubator helm repository
  become_user: vagrant
  command: helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator

- name: Add bitnami helm repository
  become_user: vagrant
  command: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Install bitnami zookeeper
  become_user: vagrant
  command: helm install zookeeper bitnami/zookeeper --set replicaCount=2 --set auth.enabled=false --set allowAnonymousLogin=true
  environment:
    KUBECONFIG: "/home/vagrant/.kube/config"

- name: Install bitnami kafka
  become_user: vagrant
  command: helm install kafka bitnami/kafka --set zookeeper.enabled=false --set replicaCount=2 --set externalZookeeper.servers=zookeeper
  environment:
    KUBECONFIG: "/home/vagrant/.kube/config"

