---
- name: Initializate cluster
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_init.txt"
  args:
    chdir: $HOME
    creates: cluster_init.txt

- name: create .kube directory
  become_user: vagrant
  file:
    remote_src: yes
    path: /home/vagrant/.kube
    state: directory
    mode: 0755

- name: Copy admin conf to user's kube conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant

- name: chown kube dir
  file:
    path: /home/vagrant/.kube/config
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: install Pod network
  shell: "kubectl -n kube-system apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt"
  args:
    creates: pod_network_setup.txt
  environment:
    KUBECONFIG: "/home/vagrant/.kube/config"

- name: install Dashboard
  shell: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml"
  environment:
    KUBECONFIG: "/home/vagrant/.kube/config"

- name: curl helm
  shell: "curl https://baltocdn.com/helm/signing.asc | sudo apt-key add - "
  args:
    warn: no

- name: install apt-transport-https
  apt:
    force: yes
    name: apt-transport-https
    state: present

- name: baltocdn all main
  shell: "echo \"deb https://baltocdn.com/helm/stable/debian/ all main\" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list"

- name: Update Cache
  apt: update_cache=yes

- name: install helm
  apt:
    force: yes
    name: helm
    state: present

