---
- name: Initializate cluster
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_init.txt"
  args:
    chdir: $HOME
    creates: cluster_init.txt

- name: create .kube directory
  become_user: vagrant
  file:
    remote_src: yes
    path: /home/vagrant/.kube
    state: directory
    mode: 0755

- name: Copy admin conf to user's kube conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant

- name: install Pod network
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt"
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: get join command
  shell: "kubeadm token create --print-join-command"
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
