# -*- mode: ruby -*-
# vi: set ft=ruby :
boxes = [
  { :name => :k8sMaster1, :ip => '192.168.33.101'},
  { :name => :k8sNode1, :ip => '192.168.33.102'},
]

Vagrant.configure("2") do |config|

  boxes.each do |opts|
    config.vm.define opts[:name] do |machine|
      machine.vm.box = "ubuntu/xenial64"
      machine.vm.network "private_network", ip: opts[:ip]
      machine.vm.hostname = opts[:name]
      config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.cpus = 2
      end
      config.ssh.forward_agent = true
      config.ssh.insert_key = false
      config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
      config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      config.vm.provision "shell", inline: <<-EOC
          sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
          sudo systemctl restart sshd.service
          echo "finished"
      EOC
      config.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y python
          echo "done install python!"
      SHELL
    end
  end
end